### Defining Variables

In [1]:
"Hello World"

'Hello World'

In [6]:
greeting = _

In [7]:
greeting

'Hello World'

In [8]:
print(greeting)

Hello World


### Basic Math

In [12]:
a = 2
b = 15

In [13]:
a + b

17

In [14]:
my_sum = _

In [15]:
my_sum

17

In [16]:
my_product = a * b

In [17]:
my_product

30

### Import Libraries

In [18]:
import numpy as np

In [19]:
ages_list = [25, 30, 35, 40, 45]

In [20]:
ages = np.array(ages_list)

In [21]:
ages_list

[25, 30, 35, 40, 45]

In [23]:
ages

array([25, 30, 35, 40, 45])

In [24]:
ages[0]
ages[1]
ages[-1]

45

In [25]:
ages[0:1]

array([25])

In [26]:
ages[ages>26]

array([30, 35, 40, 45])

In [27]:
len(ages)

5

In [28]:
[ages>26]

[array([False,  True,  True,  True,  True])]

In [30]:
np.mean(ages)

35.0

In [31]:
np.min(ages)

25

In [32]:
np.max(ages)

45